### ISSUE TITLE
Pattern Matching

### ISSUE THREAD

**Issue by forax** [forax/java-world-domination-plan#9]
[JEP 305](http://openjdk.java.net/jeps/305)

specification [http://cr.openjdk.java.net/~briangoetz/amber/pattern-match.html](http://cr.openjdk.java.net/~briangoetz/amber/pattern-match.html)

 - [x] placement of default in switch #5  
 - [x] allow primitive types when switching over object #6
 - [x] case with a parameterized type #7
